import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = {
	variable: "--font-geist-sans",
};

const geistMono = {
	variable: "--font-geist-mono",
};

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
